# Generated by Django 2.1.5 on 2019-02-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
