# Generated by Django 2.1.5 on 2019-02-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_auto_20190210_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
