# Generated by Django 2.1.5 on 2019-02-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_auto_20190210_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='asignaturas',
            field=models.ManyToManyField(to='adminApp.Asignatura'),
        ),
    ]
